packages:
  # X402 core and adapter packages
  - 'deps/x402/typescript/packages/*'
  
  # X402x SDK packages
  - 'typescript/packages/*'
  
  # Facilitator (Production-ready component)
  - 'facilitator'
  
  # Examples (use npm alias for x402, but managed in workspace for convenience)
  - 'examples/showcase/server'
  - 'examples/showcase/client'

  # Website Project
  - 'web/frontend'

  # Applications Project
  - 'apps/swap'
  - 'apps/bridge'