packages:
  # X402 
  - 'deps/x402/typescript/packages/*'
  
  # Settlement showcase 
  - 'examples/settlement-showcase/server'
  - 'examples/settlement-showcase/client'
  
  # Facilitator
  - 'examples/facilitator'
