/**
 * Settlement Routes Helper
 * 
 * Provides utilities for creating route configurations with router settlement support.
 * This module bridges the gap between x402 v2 official SDK's RoutesConfig and x402x
 * settlement requirements.
 */

import type { x402ResourceServer } from "@x402/core/server";
import type { PaymentRequirements } from "@x402/core/types";
import { createExtensionDeclaration } from "./server-extension.js";
import { getNetworkConfig } from "./networks.js";
import { TransferHook } from "./hooks/index.js";

/**
 * Route configuration from @x402/core
 * Re-exported for convenience with settlement prefix to avoid naming conflicts
 */
export interface SettlementRouteConfig {
  accepts: SettlementPaymentOption | SettlementPaymentOption[];
  resource?: string;
  description?: string;
  mimeType?: string;
  extensions?: Record<string, unknown>;
  unpaidResponseBody?: (context: unknown) => Promise<{ contentType: string; body: unknown }> | { contentType: string; body: unknown };
  customPaywallHtml?: string;
}

/**
 * Payment option from @x402/core
 */
export interface SettlementPaymentOption {
  scheme: string;
  network: string;
  payTo: string | ((context: unknown) => string | Promise<string>);
  price: string | ((context: unknown) => string | Promise<string>);
  maxTimeoutSeconds?: number;
  extra?: Record<string, unknown>;
}

/**
 * Settlement options for route configuration
 */
export interface SettlementOptions {
  /** Hook contract address (optional, defaults to TransferHook for the network) */
  hook?: string;
  /** Encoded hook data (optional, defaults to TransferHook.encode()) */
  hookData?: string;
  /** Facilitator fee amount (optional, will be dynamically calculated if not provided) */
  facilitatorFee?: string;
  /** Final recipient address (the actual merchant/payee) */
  finalPayTo: string;
  /** Optional description for the extension */
  description?: string;
}

/**
 * Configuration for settlement hooks
 */
export interface SettlementHooksConfig {
  /** Whether to enable automatic salt extraction from extension info */
  enableSaltExtraction?: boolean;
  /** Whether to validate settlement router parameters */
  validateSettlementParams?: boolean;
}

/**
 * Create a route configuration with router settlement support
 * 
 * This helper wraps the standard x402 RouteConfig and adds settlement-specific
 * configuration including hooks, settlement router address, and dynamic extensions.
 * 
 * The key insight: We add settlement info to the `extra` field of PaymentRequirements,
 * which gets passed through verify/settle. The extension generates dynamic salt per request.
 * 
 * @param baseConfig - Base route configuration
 * @param settlementOptions - Settlement-specific options
 * @returns Enhanced route configuration with settlement support
 * 
 * @example
 * ```typescript
 * import { createSettlementRouteConfig, TransferHook } from "@x402x/core_v2";
 * 
 * const routes = {
 *   "POST /api/purchase": createSettlementRouteConfig({
 *     accepts: {
 *       scheme: "exact",
 *       network: "eip155:84532",
 *       payTo: "0x...", // Will be overridden with settlementRouter
 *       price: "$1.00",
 *     },
 *     description: "Purchase endpoint",
 *   }, {
 *     hook: TransferHook.getAddress("base-sepolia"),
 *     hookData: TransferHook.encode(),
 *     finalPayTo: "0xMerchantAddress",
 *   })
 * };
 * ```
 */
export function createSettlementRouteConfig(
  baseConfig: SettlementRouteConfig,
  settlementOptions: SettlementOptions,
): SettlementRouteConfig {
  // Normalize accepts to array
  const acceptsArray = Array.isArray(baseConfig.accepts) 
    ? baseConfig.accepts 
    : [baseConfig.accepts];

  // Enhance each payment option with settlement info
  const enhancedAccepts = acceptsArray.map((option) => {
    // Extract network from the option
    const network = typeof option.network === "string" ? option.network : option.network;
    
    // Get network configuration for settlement router
    const networkConfig = getNetworkConfig(network);
    if (!networkConfig) {
      throw new Error(`Network configuration not found for: ${network}`);
    }

    // Resolve hook address (default to TransferHook)
    const hook = settlementOptions.hook || TransferHook.getAddress(network);
    const hookData = settlementOptions.hookData || TransferHook.encode();

    // Build settlement extra fields
    // Note: salt will be dynamically generated by the extension's enrichDeclaration
    const settlementExtra = {
      settlementRouter: networkConfig.settlementRouter,
      hook,
      hookData,
      payTo: settlementOptions.finalPayTo,
      facilitatorFee: settlementOptions.facilitatorFee || "0", // Will be calculated dynamically if not provided
      // EIP-712 domain info for the asset
      name: networkConfig.defaultAsset.eip712.name,
      version: networkConfig.defaultAsset.eip712.version,
    };

    // Merge settlement extra with existing extra
    const enhancedOption: SettlementPaymentOption = {
      ...option,
      // Override payTo to use settlementRouter as the immediate recipient
      payTo: networkConfig.settlementRouter,
      // Merge extra fields
      extra: {
        ...(option.extra || {}),
        ...settlementExtra,
      },
    };

    return enhancedOption;
  });

  // Add settlement extension to the route
  const extensions = {
    ...(baseConfig.extensions || {}),
    ...createExtensionDeclaration({
      description: settlementOptions.description || "Router settlement with atomic fee distribution",
    }),
  };

  return {
    ...baseConfig,
    accepts: enhancedAccepts.length === 1 ? enhancedAccepts[0] : enhancedAccepts,
    extensions,
  };
}

/**
 * Register settlement-specific hooks with the resource server
 * 
 * This function registers lifecycle hooks for handling settlement-specific logic:
 * - Extract salt from extension info before verification
 * - Validate settlement router parameters
 * 
 * @param server - x402ResourceServer instance
 * @param config - Hook configuration options
 * 
 * @example
 * ```typescript
 * import { registerSettlementHooks } from "@x402x/core_v2";
 * 
 * registerSettlementHooks(server, {
 *   enableSaltExtraction: true,
 *   validateSettlementParams: true,
 * });
 * ```
 */
export function registerSettlementHooks(
  server: x402ResourceServer,
  config: SettlementHooksConfig = {},
): void {
  const {
    enableSaltExtraction = true,
    validateSettlementParams = true,
  } = config;

  if (enableSaltExtraction) {
    // Hook to extract salt from PaymentPayload extensions and add to requirements.extra
    server.onBeforeVerify(async (context) => {
      const { paymentPayload, requirements } = context;
      
      // Check if payment has settlement extension with salt
      if (paymentPayload.extensions && 
          "x402x-router-settlement" in paymentPayload.extensions) {
        const extension = paymentPayload.extensions["x402x-router-settlement"] as any;
        
        if (extension?.info?.salt) {
          // Ensure requirements.extra exists and add the salt
          if (!requirements.extra) {
            (requirements as any).extra = {};
          }
          (requirements.extra as any).salt = extension.info.salt;
        }
      }
      
      // Don't abort - continue with verification
      return undefined;
    });
  }

  if (validateSettlementParams) {
    // Hook to validate settlement router parameters before settlement
    server.onBeforeSettle(async (context) => {
      const { requirements } = context;
      
      // Validate that required settlement fields are present
      if (requirements.extra) {
        const extra = requirements.extra as any;
        
        const requiredFields = ['settlementRouter', 'hook', 'hookData', 'payTo'];
        const missingFields = requiredFields.filter(field => !extra[field]);
        
        if (missingFields.length > 0) {
          return {
            abort: true,
            reason: `Missing settlement parameters: ${missingFields.join(', ')}`,
          };
        }
      }
      
      // All checks passed
      return undefined;
    });
  }
}

